### ISSUE TITLE
Disable EVMJIT

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/webthree-helpers#31]
As I am just interested in building Solidity and don't want to have to deal with LLVM dependencies, how can I disable EVMJIT? Is there a command line flag to specify `-DEVMJIT=0` that gets passed to `cmake` when using `ethbuild.sh`

```
webthree-helpers/scripts/ethbuild.sh --no-git --cores 16 --project solidity
```

As a workaround I can change the default in `cmake/EthOptions.cmake` to revert the recent change by @chfast

**Comment by chfast** [comment]
Sorry for the inconvenience.

`cmake -DEVMJIT=0` should do the work.

**Comment by jorisbontje** [comment]
Clarified the issue description to indicate the context of webtree-helpers here; so disabling EVMJIT when calling:
```
webthree-helpers/scripts/ethbuild.sh --no-git --cores 16 --project solidity
```

**Comment by chfast** [comment]
@LefterisJP, is it possible to disable EVMJIT in ethbuild.sh?

**Comment by LefterisJP** [comment]
Yep. Just append at the very end `-DEVMJIT=0`. 
I will edit the wiki to clarify this. Any extra arguments at the end are simply forwarded to cmake

**Comment by jorisbontje** [comment]
Thanks!
